### ISSUE TITLE
The tooltip of the drill its too large (i have a solution)

### ISSUE THREAD

**Issue by Levviata** [Kogsey/Termination-Mod#1]
for fixing that you only need to put this

("tooltiphere") 1 line

("tooltip1\ntooltip2") 2 lines

("tooltip1\ntooltip2\ntooltip3") 3 lines etc,etc.

example / code: 

https://pastebin.com/QpCtAbXP

**Comment by Levviata** [comment]
hope it helps

**Comment by Kogsey** [comment]
hey man if you wanna poke around in the code the repository I use for multi-machine work is:
https://github.com/Kogsey/Termination
but thatks for the tip - didn't realise it was so long
